name: release
on:
  push:
    # branches:
    #   - main
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
      - "v*"
defaults:
  run:
    shell: bash

jobs:
  release:
    name: release npm package
    # if: ${{ github.repository_owner == 'ymc-github' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write # allow GITHUB_TOKEN to release repo
      packages: write # allow GITHUB_TOKEN to publish packages
    steps:
      - name: checkout your repository
        uses: actions/checkout@v4

      - name: Get version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Setup PNPM
        uses: pnpm/action-setup@v3
        with:
          version: ^7.0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Build npm Packages
        run: pnpm run build

      # done
      # - name: Publish to registry.npmjs.org
      #   uses: JS-DevTools/npm-publish@v3
      #   with:
      #     token: ${{ secrets.NPM_TOKEN }}
      #     registry: "https://registry.npmjs.org/"
      #     dry-run: true
      # # Package name must be a string, got "undefined" when mono repo.

      - name: npm publish to registry.npmjs.org
        # run: npm publish --workspaces --dry-run
        run: |
          npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
          npm publish --workspaces --dry-run
        shell: bash
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      # please create org and sign before publishing private pkg
      - name: pnpm publish to registry.npmjs.org
        run: |
          # pnpm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
          pnpm -r publish --no-git-checks --access public
        shell: bash
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      # https://npm.pkg.github.com/
      - name: pnpm publish to npm.pkg.github.com
        run: |
          pnpm set registry https://npm.pkg.github.com/
          pnpm -r publish --no-git-checks --dry-run
        shell: bash
        env:
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # done
      - name: Create github Release
        uses: softprops/action-gh-release@v2
        with:
          body_path: README.md
          # note you'll typically need to create a personal access token
          # with permissions to create releases in the other repo
          token: ${{ secrets.GITHUB_TOKEN }}
